POST https://u19x53aisk.execute-api.us-east-1.amazonaws.com/actionable/signup
Content-Type: application/json

{
  "email": "victorrbravo7@gmail.com",
  "name": "Sol1",
  "last_name": "Sole",
  "phone": "+573162811255",
  "password": "123456",
  "password_confirmation": "123456",
  "gender" : "M",
  "username": "solecito1"
}


###
GET http://localhost:8081/confirm?code=lgDq4n7d
Accept: application/json

###
GET  https://t0ggpzn2k3.execute-api.us-east-1.amazonaws.com/stage/confirm?code=ml8h5I6N
Accept: application/json

###
###
POST https://t0ggpzn2k3.execute-api.us-east-1.amazonaws.com/stage/signup
Content-Type: application/json

{
  "email": "victorrbravo7@gmail.com",
  "name": "Solazver",
  "username": "solaz",
  "last_name": "Sole",
  "phone": "+573162821255",
  "password": "123456",
  "password_confirmation": "123456",
  "gender" : "M"
}


###
GET http://localhost:8081/confirm?code=lgDq4n7d
Accept: application/json

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "email": "victorrbravo@gmail.com",
  "password": "123456"
}

###
POST http://localhost:8081/signup
Content-Type: application/json

{
  "email": "victorrbravo2@gmail.com",
  "name": "Solazver",
  "last_name": "Sole",
  "phone": "+573162811255",
  "password": "123456",
  "password_confirmation": "123456",
  "gender" : "M",
  "username": "solecito"
}

###
